services:
  - type: web
    name: tampertrace-app
    env: docker
    plan: free
    region: ohio
    healthCheckPath: /api
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: tampertrace-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: STORAGE_PATH
        value: /var/data/storage


databases:
  - name: tampertrace-db
    plan: free
    region: ohio
